version: "3.8"

services:
  frontend:
    container_name: saku-tani-dashboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:80"
    env_file:
      - ${ENV_FILE}
