version: "3.8"

services:
  frontend:
    image: saku-tani-dashboard
    container_name: saku-tani-dashboard-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:5173"
    env_file:
      - ${ENV_FILE}
